[build-system]
requires = [
    "pybind11",
    "scikit-build-core @ git+https://github.com/henryiii/scikit-build-core",
    "setuptools_scm",
]
build-backend = "scikit_build_core.setuptools.build_meta"

[tool.isort]
profile = "black"

[tool.cibuildwheel]
test-command = "pytest {project}/tests"
test-extras = ["test"]
test-skip = ["*universal2:arm64"]
