[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11~=2.6.0",
    "cmake",
    "scikit-build @ git+https://github.com/scikit-build/scikit-build.git@8a0f9cec587ecfbfde1bbfb845841c1b4c57011b",
]
build-backend = "setuptools.build_meta"
